name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

      spring.datasource.url: ${{ secrets.JDBC_URL }}
      spring.datasource.username: ${{ secrets.DB_USERNAME }}
      spring.datasource.password: ${{ secrets.DB_PASSWORD }}
      spring.jpa.hibernate.ddl-auto: ${{ vars.SPRING_JPA_HIBERNATE_DDL_AUTO }}
      spring.jpa.properties.hibernate.dialect: ${{ vars.SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT }}
      spring.datasource.driver-class-name: ${{ vars.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}

      showtimesquad.app.jwtCookieName: ${{ vars.JWT_NAME }}
      showtimesquad.app.jwtSecret: ${{ secrets.JWT_SECRET }}
      showtimesquad.app.jwtExpirationMs: ${{ vars.JWT_EXPIRATION_MS }}

      FRONTEND_URL: ${{ vars.CORS_FRONTEND_URL }}

    defaults:
      run:
        working-directory: showtime-squad_backend

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

